### ISSUE TITLE
Unable to set up extension for docker deployment

### ISSUE THREAD

**Issue by Zutart** [ndom91/briefkasten#12]
### Describe the bug

When attempting to set up the chrome extension for use with a docker instance, it instantly fails with a "Connection failed" error. The logs show an issue with SUPABASE, however:

```
today at 12:23:09 PMError: Missing env.SUPABASE_URL
today at 12:23:09 PM    at Object.671 (/app/.next/server/chunks/220.js:71:38)
today at 12:23:09 PM    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
today at 12:23:09 PM    at Object.2726 (/app/.next/server/pages/api/bookmarks.js:102:77)
today at 12:23:09 PM    at __webpack_require__ (/app/.next/server/webpack-api-runtime.js:25:42)
today at 12:23:09 PM    at __webpack_exec__ (/app/.next/server/pages/api/bookmarks.js:483:39)
today at 12:23:09 PM    at /app/.next/server/pages/api/bookmarks.js:484:70
today at 12:23:09 PM    at Function.__webpack_require__.X (/app/.next/server/webpack-api-runtime.js:108:21)
today at 12:23:09 PM    at /app/.next/server/pages/api/bookmarks.js:484:47
today at 12:23:09 PM    at Object.<anonymous> (/app/.next/server/pages/api/bookmarks.js:487:3)
today at 12:23:09 PM    at Module._compile (node:internal/modules/cjs/loader:1126:14)
```

**Expected Results** - Using the base URL and the provided API key, extension would be set up. Based on documentation, Supabase was not a requirement.

Attempts to browse to the api (https://briefkasten.tld/api/*) are unsuccessful, as are test attempts at directly posting to the API through a direct POST request.

### Reproduction

1. Install official extension
2. Put in base url (https://briefkasten.tld) and token
3. Instant failure to connect

### System Info

```Shell
System:
    OS: Linux 5.4 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (2) x64 AMD PRO A4-8350B R5, 6 Compute Cores 2C+4G
    Memory: 25.79 GB / 30.32 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 16.17.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.15.0 - /usr/local/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by Zutart** [comment]
Quick update - decided to try and add a bookmark manually through the web gui and ran into the same error / log message. Assumption is that Supabase (or equivalent) is required at this point, but would love to know if I'm doing something wrong.

**Comment by ndom91** [comment]
> Quick update - decided to try and add a bookmark manually through the web gui and ran into the same error / log message. Assumption is that Supabase (or equivalent) is required at this point, but would love to know if I'm doing something wrong.

Hey @Zutart thanks for flagging this. I justtt released this the other day and while manual testing in my environment worked, there could obviously still be bugs 😅 I think youre one of the first to officially try the docker methodology. 

So anyway, let me get this straight, you did not supply a supabase env var and do not want to use it? 

I'll double check this a bit later on when I'm home 👍

**Comment by Zutart** [comment]
Hey @ndom91 just realized how fresh the docker deployment is, good timing on my part I suppose!

Yeah I was just trying to stand up the project and see how it looked / how the extensions worked and didn't want to go the route of setting up Supabase immediately. I went ahead and did so just now to test and as soon as I provided the URL and key everything worked as expected.

Would be interested in not necessarily having to go that route but not the end of the world otherwise. I also just tested the profile link to see what was there and got a page not found issue. Obviously not the same thing as above but wanted to just mention it here before I forgot.

**Comment by ndom91** [comment]
> Hey @ndom91 just realized how fresh the docker deployment is, good timing on my part I suppose!
> 
> Yeah I was just trying to stand up the project and see how it looked / how the extensions worked and didn't want to go the route of setting up Supabase immediately. I went ahead and did so just now to test and as soon as I provided the URL and key everything worked as expected.
> 
> Would be interested in not necessarily having to go that route but not the end of the world otherwise. I also just tested the profile link to see what was there and got a page not found issue. Obviously not the same thing as above but wanted to just mention it here before I forgot.

Okay awesome, good to hear. 

Yeah makes sense that you'd want to be able to spin it up quickly to take a look without having to signup for supabase or any other service. Although the demo / cloud instance is also available for a quick peak. 

I'll still take a look at this though, I definitely want it to run without having to provide a `SUPABASE_URL` or any other online service. 

Also that profile page doesn't exist yet, only the settings one does. I should definitely disable/remove that button 👍

**Comment by ndom91** [comment]
@Zutart I was able to reproduce the issue on my end. Let me see if I can ship a fix for it real quick :+1:

**Comment by ndom91** [comment]
I'm going to close this as "Solved". If yuo still have an issue, please open a new issue or comment to reopen this :+1:
