### ISSUE TITLE
Supabase URL not being picked by 

### ISSUE THREAD

**Issue by shubhank-saxena** [ndom91/briefkasten#14]
### Describe the bug

Supabase is not being utilised. I already have set up SUPABASE_URL and SUPABASE_KEY in `.env`

```
wait  - compiling /api/bookmarks...
event - compiled successfully in 655 ms (117 modules)
SUPABASE_KEY, SUPABASE_URL or SUPABASE_BUCKET_ID missing - will not upload screenshots.
[next-auth][warn][EXPERIMENTAL_API]
`unstable_getServerSession` is experimental and may be removed or changed in the future, as the name suggested.
https://next-auth.js.org/configuration/nextjs#unstable_getServerSession}
https://next-auth.js.org/warnings#EXPERIMENTAL_API
[next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
[next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
[next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
[next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
```

### Reproduction

Save a bookmark

### System Info

```Shell
System:
    OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
    CPU: (4) arm64 unknown
    Memory: 652.97 MB / 3.72 GB
    Container: Yes
    Shell: 5.1.4 - /bin/bash
  Binaries:
    Node: 14.19.3 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 6.14.17 - /usr/bin/npm
  Browsers:
    Firefox: 91.9.1esr
```

### Used Package Manager

pnpm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
> ### Describe the bug
> 
> Supabase is not being utilised. I already have set up SUPABASE_URL and SUPABASE_KEY in `.env`
> 
> ```
> wait  - compiling /api/bookmarks...
> event - compiled successfully in 655 ms (117 modules)
> SUPABASE_KEY, SUPABASE_URL or SUPABASE_BUCKET_ID missing - will not upload screenshots.
> [next-auth][warn][EXPERIMENTAL_API]
> `unstable_getServerSession` is experimental and may be removed or changed in the future, as the name suggested.
> https://next-auth.js.org/configuration/nextjs#unstable_getServerSession}
> https://next-auth.js.org/warnings#EXPERIMENTAL_API
> [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> ```
> 
> ### Reproduction
> 
> Save a bookmark
> 
> ### System Info
> 
> ```Shell
> System:
>     OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
>     CPU: (4) arm64 unknown
>     Memory: 652.97 MB / 3.72 GB
>     Container: Yes
>     Shell: 5.1.4 - /bin/bash
>   Binaries:
>     Node: 14.19.3 - /usr/bin/node
>     Yarn: 1.22.19 - /usr/bin/yarn
>     npm: 6.14.17 - /usr/bin/npm
>   Browsers:
>     Firefox: 91.9.1esr
> ```
> 
> 
> ### Used Package Manager
> 
> pnpm
> 
> ### Validations
> 
> - [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> - [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> - [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

There's an additional key, `SUPABASE_BUCKET_ID` for the supabase storage bucket which should hold images. Very recently added, might not be in the docs yet 🙈 I'll add it shortly.

**Comment by ndom91** [comment]
> > ### Describe the bug
> > 
> > Supabase is not being utilised. I already have set up SUPABASE_URL and SUPABASE_KEY in `.env`
> > 
> > ```
> > wait  - compiling /api/bookmarks...
> > event - compiled successfully in 655 ms (117 modules)
> > SUPABASE_KEY, SUPABASE_URL or SUPABASE_BUCKET_ID missing - will not upload screenshots.
> > [next-auth][warn][EXPERIMENTAL_API]
> > `unstable_getServerSession` is experimental and may be removed or changed in the future, as the name suggested.
> > https://next-auth.js.org/configuration/nextjs#unstable_getServerSession}
> > https://next-auth.js.org/warnings#EXPERIMENTAL_API
> > [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> > [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> > [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> > [next-auth][debug][adapter_getSessionAndUser] { args: [ '313c24b3-2b4f-4ce0-b1dc-f867c0178d1d' ] }
> > ```
> > 
> > ### Reproduction
> > 
> > Save a bookmark
> > 
> > ### System Info
> > 
> > ```Shell
> > System:
> >     OS: Linux 5.15 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
> >     CPU: (4) arm64 unknown
> >     Memory: 652.97 MB / 3.72 GB
> >     Container: Yes
> >     Shell: 5.1.4 - /bin/bash
> >   Binaries:
> >     Node: 14.19.3 - /usr/bin/node
> >     Yarn: 1.22.19 - /usr/bin/yarn
> >     npm: 6.14.17 - /usr/bin/npm
> >   Browsers:
> >     Firefox: 91.9.1esr
> > ```
> > 
> > 
> > ### Used Package Manager
> > 
> > pnpm
> > 
> > ### Validations
> > 
> > - [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> > - [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> > - [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
> 
> There's an additional key, `SUPABASE_BUCKET_ID` for the supabase storage bucket which should hold images. Very recently added, might not be in the docs yet 🙈 I'll add it shortly. 
> 
> Is it saving the bookmarks anyway though? Your just seeing this console warning? 
> 
> Cause I've disabled taking screenshots when adding a bookmark for the moment anyway. Was slowing things down too much and causing the Vercel api route (in the demo instance) to time out (taking more than 10s). 

In the demo instance of mine, I have the [briefkasten-scraper](https://github.com/ndom91/briefkasten-scraper) running ever few hrs in a GH Action and filling in missing screenshots. Need to find a solution for self-hosters for the screenshots 🤔

**Comment by shubhank-saxena** [comment]
Oh, I see. Sorry wasn't aware of the latest changes.
Yes. It's saving the bookmarks.
Can we save it natively where server is running?

**Comment by ndom91** [comment]
Yeah thats not a bad idea. In self-hosted docker setup, we could just generate them and save them to disk.

Also in self-hosted mode the user will probably have a more powerful system than whatever Lambda's Vercel use for Next.js API Routes. Meaning it shouldn't take ~10s. But even if it does, it'll also not timeout and fail after 10s in self-hosted environments! Hurray for running ones own infra haha. 

I'll take a look at making this change and making it transparent :+1:

**Comment by ndom91** [comment]
Core issue with supabase url is fixed. Secondary issue regarding self hosters image generation is still WIP and being tracked [here](https://github.com/ndom91/briefkasten/issues/42). Closing this issue :+1:
