### ISSUE TITLE
Publish docker container

### ISSUE THREAD

**Issue by stavros-k** [ndom91/briefkasten#21]
### Clear and concise description of the problem

Would be nice to have a docker container published in a repository like ghcr, dockerhub etc
So downstreams like packagers for platforms (eg Unraid, TrueNAS Scale, etc) can use it

### Suggested solution

Publish docker container

### Alternative

Have downstreams to build their own, and potentially have bugs coming that are not really this project's fault. 
But a fault of a bad built image

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
Hey I really appreciate the truecharts work!

I'll get to publishing this and ping you back if you want to attempt that again then :+1:

**Comment by ndom91** [comment]
Finally got around to publishing an official copy of this image!

https://hub.docker.com/repository/docker/ndom91/briefkasten

**Comment by stavros-k** [comment]
@ndom91 Hey, seems to be a small issue with the container.
On startup it complains about `sentry`

```shell
warn  - Invalid next.config.js options detected: 
  - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
```

Which seems to coming from this:

https://github.com/ndom91/briefkasten/blob/03aa6d390ac06eb1357cb96f0f841054eb4dfe35/next.config.mjs#L18-L20

Is there anything I can do on my side?

**Comment by ndom91** [comment]
> @ndom91 Hey, seems to be a small issue with the container.
> On startup it complains about `sentry`
> 
> ```shell
> warn  - Invalid next.config.js options detected: 
>   - The root value has an unexpected property, sentry, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).
> ```
> 
> Which seems to coming from this:
> 
> https://github.com/ndom91/briefkasten/blob/03aa6d390ac06eb1357cb96f0f841054eb4dfe35/next.config.mjs#L18-L20
> 
> Is there anything I can do on my side?

Hey no so you can just ignore this, its okay. 

It's because next.js doesn't have `sentry` as a whitelisted object in its config, but it's clearly still okay to have it there. It's only a `warn` level event, right. Not an `error` 👍

**Comment by stavros-k** [comment]
> Hey no so you can just ignore this, its okay.
> 
> It's because next.js doesn't have `sentry` as a whitelisted object in its config, but it's clearly still okay to have it there. It's only a `warn` level event, right. Not an `error` 👍

Duh..., For some reason I never saw the `warn` and was stuck investigating this instead of moving on the `TypeError` right after it.
Thinking that when I solve the above it will probably solve the rest -.-

So this is what I get, and trying to access the webUI returns 500.

I've set this env's `NEXTAUTH_URL`, `NEXTAUTH_SECRET`, `DATABASE_URL`.

```shell
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Signin (/app/.next/server/pages/auth/signin.js:57:43)
    at Wc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:68:44)
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:70:253)
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
    at $c (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:78:98)
    at bd (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:77:404)
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:217)
    at Zc (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:74:209)
    at Z (/app/node_modules/.pnpm/react-dom@18.2.0_react@18.2.0/node_modules/react-dom/cjs/react-dom-server.browser.production.min.js:76:89)
```

Let me know if you want me to turn this into a new issue. for tracking.
