### ISSUE TITLE
Installation unter Docker oder auf einem Synology NAS

### ISSUE THREAD

**Issue by itelo24** [ndom91/briefkasten#3]
Hallo,
hat schon mal jemand die App unter Synology bzw. Docker installiert ?
Vielen Dank.

**Comment by ndom91** [comment]
Hi @itelo24,

Kann man bei Synology DSM Docker container laufen lassen? 

Wenn ja, konntest du diese ziemlich standard Next.js application in einem node basierenden container laufen lassen. Hier ist ein link zu ["Next.js self-hosting in Docker"](https://nextjs.org/docs/deployment#docker-image) von deren Docs. Die empfehlen da die `with-docker` example app zu clonen, aber eigentlich brauchst du nur die `Dockerfile` aus deren beispiel repo (https://github.com/vercel/next.js/blob/canary/examples/with-docker/Dockerfile) und die dann bisschen anpassen. Daraufhin dann die ["in existing projects"](https://github.com/vercel/next.js/tree/canary/examples/with-docker#in-existing-projects) config anderungen auch hier in der `next.config.js` setzen.

Wenn nicht, musstest du mal schauen ob man Node.js 14+ (aber am besten 16) mit npm irgendwie darauf installieren kann. Dann konntest du mit ner shell einfach diese repository clonen, die anleitung in der README folgen (env vars, etc.), und mit [`pm2`](https://pm2.keymetrics.io/docs/usage/quick-start/) bsplw. langfristig laufen lassen.

**Comment by itelo24** [comment]
Vielen Dank für die Antowrt. Das ist mir aber zu kompliziert. Dann muß ich wohl was anderes nehmen.
