### ISSUE TITLE
Self-hosting with docker: how to fetch thumbnails?

### ISSUE THREAD

**Issue by ingeniumstudio** [ndom91/briefkasten#32]
Hello,

I just installed briefkasten using docker, everything is working except that it just fetches placeholder images, how can I make it work?

I am using supabase.

Also, can the images be hosted locally? (it's running on an archlinux vps at aws; EDIT: served via Apache reverse proxy)

thanks for the awesome app.

**Comment by ingeniumstudio** [comment]
I managed to do it:

1. Making the Supabase bucket public.
2. Fixing (at least for me) the `briefkasten-scrape`. (I'm running it via a cronjob, it's documented on my fork's `README.md`)

Please, if you have time, see if you're interested in a pull request with the changes I've made:

https://github.com/ingeniumstudio/briefkasten-scrape

**Comment by ndom91** [comment]
Yeah perfect, this is great! Haha

I clearly failed to document how to do the screenshot grabbing with self hosted setups, so lots of people have opened issues / privately asked me. But this is one very valid way to do it.

A little background info: I initially had it setup to start playwright, visit the URL beign saved, and then save that URL to a bucket and the bookmark details to the database all in one Next.js API route. Unfortuantely that whole playwright startup and screenshot process often took 10+ seconds. Causing that API route to timeout when hosted on Vercel (which is what I do with the demo instance / I assumed many others would do as well). It quickly became very annoying that I coudln't even save bookmarks just becaues the screenshot process was timing out.

So I decoupled the screenshotting from the saving bookmark details to the DB process, which resulted in the current setup. An separate repo / project for an async scrape job. In the demo instance I have it running from a message queue on inngest.com. A new async screenshot grabbing job is triggered anytime a new URL is added to the DB.

**Comment by ndom91** [comment]
You've got some very nice changes in there. Could you open a PR?

**Comment by kgnfth** [comment]
How to use it without supabase ? please

**Comment by mmintel** [comment]
I wrote a blog article to help with this, hope that helps someone https://mintel.me/how-to-install-briefkasten-using-docker/

**Comment by ndom91** [comment]
> I wrote a blog article to help with this, hope that helps someone https://mintel.me/how-to-install-briefkasten-using-docker/
> 
> @kgnfth 

Hey thanks a lot for writing this up! The `briefkasten-scrape` sister repo, as you've found out, is definitely not designed for self hosters to easily consume 😅 

I was thinking for selfhosters, if they're not using a paas service like Vercel or netlify, they most likely have access to more powerful hardware than the Vercel serverless functions run on (low memory aws Lambda instances), and so just including the playwright based api route might make sense for them. They won't run into the 10s runtime limitations, nor the 50mb function size limits from Vercel. And simply having 1 api route baked into the main briefkasten repo/project would make this whole process much easier. 

Thoughts?

**Comment by mmintel** [comment]
> > I wrote a blog article to help with this, hope that helps someone https://mintel.me/how-to-install-briefkasten-using-docker/
> > @kgnfth
> 
> Hey thanks a lot for writing this up! The `briefkasten-scrape` sister repo, as you've found out, is definitely not designed for self hosters to easily consume 😅
> 
> I was thinking for selfhosters, if they're not using a paas service like Vercel or netlify, they most likely have access to more powerful hardware than the Vercel serverless functions run on (low memory aws Lambda instances), and so just including the playwright based api route might make sense for them. They won't run into the 10s runtime limitations, nor the 50mb function size limits from Vercel. And simply having 1 api route baked into the main briefkasten repo/project would make this whole process much easier.
> 
> Thoughts?

I don't know about the limitations of vercel but normally you would have a client and a server, I think you place too much logic into the Nextjs instance. If you have a server that handles image generation and saving of the bookmarks you would just call the servers API from Nextjs and vercel wouldn't probably even care.

**Comment by ndom91** [comment]
Closing this issue as the reasons are described above.
