### ISSUE TITLE
Importing chrome bookmark html fails

### ISSUE THREAD

**Issue by FabriceBoyer** [ndom91/briefkasten#35]
### Describe the bug

export chrome bookmarks in html (not sure if same "standard" than the one you expect though)
file is valid and contains hundreds of links
try to import it in briefkasten
=> 0 imported

### Reproduction

export chrome bookmarks in html => try to import it in briefkasten => 0 imported

### System Info

```Shell
tested on your instance at https://briefkastenhq.com/
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by FabriceBoyer** [comment]
Indeed, I got the same error than you in console. So this import feature probably doesn't work at all ...

I'm on chrome (latest stable) and I tried to disable all my extensions (but it didn't change anything)

Hope it will be fixed, this software looks interesting but is useless for me without this import feature

**Comment by rauschgiftengel** [comment]
Same issue with the docker installation.

If you click on that import button without loading a file it looks like its working, there is a green banner wich states that 0 bookmarks has been imported. But with a file loaded it does exactly nothing.

Offtopic: Maybe you should mention the fact that one has to provide at least one login method in the .env file. Took me hours of testing an finaly found that info in a closed issue. Maybe let the user choose the login methode. Have been testing Neonlink wich is exactly that, easy setup, clear guide, an just doing what it is made for. (but without a companion app, thats why i test your app now - actualy bit disapointed)

**Comment by gummipunkt** [comment]
Hi,

tried this to in my docker version with a import from a raindrop.io export:

`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at settings-1af68e85f6c9ca52.js:1:7754
    at Array.map (<anonymous>)
    at k (settings-1af68e85f6c9ca52.js:1:7480)
    at Object.e7 (framework-c87cbe29bcbbc912.js:9:16667)
    at eU (framework-c87cbe29bcbbc912.js:9:16821)
    at framework-c87cbe29bcbbc912.js:9:35490
    at r$ (framework-c87cbe29bcbbc912.js:9:35589)
    at rg (framework-c87cbe29bcbbc912.js:9:36003)
    at framework-c87cbe29bcbbc912.js:9:41461
    at oU (framework-c87cbe29bcbbc912.js:9:104356)`

**Comment by ndom91** [comment]
Yeah theres clearly something wrong with the import process, some field (`value`) that it doesn't like. Although I successfully imported my bookmarks from Brave initially. I'll take a look at this when I have a few minutes 🙏

**Comment by ndom91** [comment]
Okay I think I've found the issue and fixed it in the latest commit. It's deployed on the briefkastenhq.com instance 👍

**Comment by FabriceBoyer** [comment]
I've tested on the briefkastenhq and also on my (updated) local instance and the result is the same : nothing happens when I press "Import". Not even a "0 imported" message as before ...

I got this error on my console : `"Uncaught (in promise) SyntaxError: Unexpected token 'B', "Body excee"... is not valid JSON" ` since its trying to parse `"Body exceeded 1mb limit"`

How can I increase this 1mb limit on my selfhosted instance ? The nginx proxy already is configured with `client_max_body_size 0;` A proper message on the web ui would be welcome too...

Otherwise thanks for your work and reactivity. I hope to see this software improve and evolve with new features !

**Comment by FabriceBoyer** [comment]
After trimming my file below 1Mb to test, the import fails with message `Error saving imported bookmarks URL already exists`
It seems it's not doing any deduplication... 
(as a side node, dead link checking would also be a nice extra)

**Comment by gummipunkt** [comment]
> I've tested on the briefkastenhq and also on my (updated) local instance and the result is the same : nothing happens when I press "Import". Not even a "0 imported" message as before ...

My raindrop.io export html file also still failed with no output. console output is Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value') at settings-1af68e85f6c9ca52.js

**Comment by ndom91** [comment]
Okay theres some good feedback here, thanks everyone!

1. So I tried to use Prisma's `upsert` method (which inserts/updates depending on if the record exists already). Unfrotunately I want to batch insert all of the imported bookmarks, right. So I had been using `createMany`, and there just isn't a batch `upsert` method in Prisma (i.e. `upsertMany`). I'll ahve to see if its still performant to loop over each individual bookmark and `upsert` them one-by-one.

2. Regarding the max body size - I've updated the `main` branch code to support up to 25mb from Next.js's side. As you mentioned, you may need to adjust any reverse proxy config, like nginx.

@gummipunkt this error message sounds like its still usign the older version. Are you selfhosting using the docker image? Standalone? Or on the cloud instance? Can yuo provide more information. Thanks!

**Comment by gummipunkt** [comment]
> @gummipunkt this error message sounds like its still usign the older version. Are you selfhosting using the docker image? Standalone? Or on the cloud instance? Can yuo provide more information. Thanks!

Hi,

you're right, looks like git pull didn't worked out well. I'm using the docker version. Now git pull worked well. But it didn't helped. Now the uploaded file didn't just dispear, the file name stays in the section and the error message in the console is:

```
settings-1af68e85f6c9ca52.js:1 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'value')
    at settings-1af68e85f6c9ca52.js:1:7754
    at Array.map (<anonymous>)
    at k (settings-1af68e85f6c9ca52.js:1:7480)
    at Object.e7 (framework-c87cbe29bcbbc912.js:9:16667)
    at eU (framework-c87cbe29bcbbc912.js:9:16821)
    at framework-c87cbe29bcbbc912.js:9:35490
    at r$ (framework-c87cbe29bcbbc912.js:9:35589)
    at rg (framework-c87cbe29bcbbc912.js:9:36003)
    at framework-c87cbe29bcbbc912.js:9:41461
    at oU (framework-c87cbe29bcbbc912.js:9:104356)
```

Thanks for your help!

**Comment by ndom91** [comment]
@gummipunkt I hate to say it, but I think your git pull might not have worked again 😅. There's no more `.value` calls in the `settings` file. They've been refactored out. 

Can you double check? Thanks!

**Comment by ndom91** [comment]
Edit: Updates are on docker hub now as well. Added a github action to auto publish there now on new changes 👍

**Comment by ndom91** [comment]
Closing, this should be working now :+1: 

Feel free to open a new issue if anyone still is seeing this issue!
