### ISSUE TITLE
Multi arch docker file

### ISSUE THREAD

**Issue by phampyk** [ndom91/briefkasten#39]
### Clear and concise description of the problem

It would be amazing if you could build a multi arch docker container. I prefer to have pre built dockers as I'm sure to have them updated without check each github for updates. 
It can be built on arm64 (rpi 4) as I have it running right now without any issues, but it would be amazing to have it pre-built by default if possible.

Thank you for developing it, I've been looking for a nice looking bookmark manager for a while now. It's great.

### Suggested solution

add different arch in the dockerfile before build and push

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
@phampyk great idea! I've added docker multi-arch builds to the build and push github action in this repository. Unfortunately prisma (one of the core libraries used in Briefkasten), doesn't support `armv7`. Meaning we can't support the Raspberry Pi 3B+, only rpi 4 and newer (`arm64`).

In short, the docker hub image `ndom91/briefkasten` is now built for both `amd64`/`arm64` :partying_face:
