### ISSUE TITLE
Tag can't be saved

### ISSUE THREAD

**Issue by ingeniumstudio** [ndom91/briefkasten#43]
### Describe the bug

The tag is created, bug a toast saying that it wasn't saved shows up..

Installed via docker

Everything works. I just need to know if you can have an idea on why this is happening,

thanks (also, is discussions closed?)

EDIT: also, I can add tags to bookmarks, but can't remove
EDIT2: same in Chrome

I'm using firefox for Android (nightly)

### Reproduction

https://i.imgur.com/gaU19S7.png

### System Info

```sh
System:
    OS: Linux 6.1 Arch Linux
    CPU: (2) x64 Intel(R) Xeon(R) CPU @ 2.20GHz
    Memory: 965.12 MB / 1.93 GB
    Container: Yes
    Shell: 5.9 - /usr/bin/zsh
  Binaries:
    Node: 19.7.0 - /usr/bin/node
    Yarn: 1.22.19 - /usr/bin/yarn
    npm: 8.19.2 - /usr/bin/npm
```

### Used Package Manager

n/a

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Hi @ingeniumstudio thanks for bringing this to my attention.

So adding tags from the sidebar is working for you? You just get an error toast message?

You should be abel to remove a tag from a bookmark from the bookmarks edit side bar.

![image](https://user-images.githubusercontent.com/7415984/231902037-de0c7c07-1f98-4671-ad9e-63e35fd850bb.png)

![image](https://user-images.githubusercontent.com/7415984/231901959-dcbf10ff-7096-4c64-8e63-d5914d314422.png)

Also discussions were never enabled before, but I did just enable them :partying_face:

**Comment by ndom91** [comment]
Confirmed tag cannot be removed. Closing this in favor of: https://github.com/ndom91/briefkasten/issues/57
