### ISSUE TITLE
Allow to disable sign up

### ISSUE THREAD

**Issue by TheZoker** [ndom91/briefkasten#45]
### Clear and concise description of the problem

I'm using github as oauth provider and so far it worked without any issue (although it would be very nice, if the callback url could be added to the docs 😅).
But now I don't want anyone else to register to my instance, since I'm the only one using it. 
It would be nice if there was a environment variable (let's say `DISABLE_REGISTRATION`) or something, to prevent new users from registering. I know that I can customize the code, but since I'm running briefkasten in a docker environment using the pre-build image this is not really an option. 
I can imagine that this is quite a popular use case, that once all member have registered, the admin wants to disable further registrations, so his instance it not used by the whole wide world. 

### Suggested solution

Add environment variable that disabled further registration.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by TheZoker** [comment]
Alright, I will have a look if I manage to open a PR. Thanks for the hints!

**Comment by ndom91** [comment]
Closing this issue as I don't have the bandwidth for this atm.
