### ISSUE TITLE
Unable to install via docker-compose: Incorrect docker-version error

### ISSUE THREAD

**Issue by MasterKryszn** [ndom91/briefkasten#47]
### Describe the bug

I can get briefkasten up and "running" but the page that loads is a 500 error saying the page I am looking for cannot be found.

Not sure if this is related to the current build? When I try running everything default I get an error from docker stating the version (3.8) is not compatible. I've tried running on other versions but keep getting similar errors. 

### Reproduction

n/a

### System Info

```Shell
n/a
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
Going to close this for now. Upgrading your `docker`/`docker-compose` to the latest version, which supports version `3.8` of the compose file format, should fix it.
