### ISSUE TITLE
Service 'app' failed to build : Build failed

### ISSUE THREAD

**Issue by QuantaNeon** [ndom91/briefkasten#50]
i am on arm64 ubuntu
using docker compose, just ran sudo docker compose up -d
https://pastebin.com/J6P97sbD

heres the .env
![image](https://user-images.githubusercontent.com/84242952/228910505-233d4412-2c3f-4022-a58b-7270e54b8172.png)

**Comment by ndom91** [comment]
Hey thansk for bringing this to my attention. Seems that `pnpm` updated their lock file format.

I've updated the `pnpm-lock.yaml` file in the `main` branch. If you pull a fresh copy you should be good to go to try the docker-compose command again.

**Comment by ndom91** [comment]
Closing this issue for now, feel free to open a new one. If you do though, please include more error output :blush:
