### ISSUE TITLE
Android Share Error

### ISSUE THREAD

**Issue by TheSelox** [ndom91/briefkasten#54]
### Describe the bug

I followed the guide in the docs on how to implement the HTTP shortcut.
All variables have been changed and when I share something with the new shortcut it works but also throws an error.
However, the bookmark is still created in the web app, but without any possibility to edit the title or tags.

Error on phone:
`Briefkasten failed with status code 500 (Internal Server Error)`

Error in docker logs:
```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
TypeError: Cannot read properties of undefined (reading 'includes')
    at handler (/app/.next/server/pages/api/bookmarks.js:365:49)
    at async /app/node_modules/.pnpm/@sentry+nextjs@7.36.0_next@13.1.6_react@18.2.0/node_modules/@sentry/nextjs/cjs/server/wrapApiHandlerWithSentry.js:143:33
    at async Object.apiResolver (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/api-utils/node.js:372:9)
    at async NextNodeServer.runApi (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:488:9)
    at async Object.fn (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:751:37)
    at async Router.execute (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/router.js:253:36)
    at async NextNodeServer.run (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:384:29)
    at async NextNodeServer.handleRequest (/app/node_modules/.pnpm/next@13.1.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/base-server.js:322:20)
```

### Reproduction

Add HTTP shortcut and try to share any link

### System Info

```Shell
Pixel 6 Android 13 (latest update)
Briefkasten Docker
```

### Used Package Manager

npm

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ndom91** [comment]
I just pushed a small update to `main` which would handle ^^, can you pull the latest code and check? Thanks :pray:

**Comment by TheSelox** [comment]
I tried it again after pulling the changes to the container but nothing changed.
Can I see somewhere if I'm really on the latest state?

I'm only calling the API via FQDN and TLS over nginx proxy manager - internally and externally.
I tried it within my LAN and from an external IP via mobile data - both results were the same.
As I said the link gets added to briefkasten, but there is no way to change any values and the errors appear.

**Comment by TheSelox** [comment]
I'm running it using Docker. Pull doesn't get any newer images so I guess I'm running the latest version

**Comment by ndom91** [comment]
On your docker host, can you run the command `docker image ls -a`. That should give you a little table of all your images. If theres too many to sort through, you can filter it to just briefkasten images with `docker image ls -a --filter reference=*briefkasten*`.

Can you share that output here? Thanks!

**Comment by TheSelox** [comment]
```
# docker image ls -a --filter reference=*briefkasten*
REPOSITORY           TAG       IMAGE ID       CREATED       SIZE
briefkasten-app      latest    f3fed140ec45   7 days ago    927MB
briefkasten-scrape   latest    253fb52a85cd   2 weeks ago   2.89GB
```

**Comment by ndom91** [comment]
Closing this issue, this should be fixed in `ndom91/briefkasten:latest` on docker hub :+1: 

Feel free to reopen if you're still having this issue
