### ISSUE TITLE
Allow changing port 3000

### ISSUE THREAD

**Issue by AeliusSaionji** [ndom91/briefkasten#61]
### Clear and concise description of the problem

I have another self hosted doodad using port 3000 already, and I can't figure out how to make briefkasten use a different port.

### Suggested solution

It would be nice to change this from the .env file.

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
If you're using Docker, then the option that @zackchadwick mentioned is definitely a valid method. 

I'm going to close this for now. If you can't get it to work, or are not using Docker, feel free to reply to reopen :+1:
