### ISSUE TITLE
Öffentliche Lesezeichen

### ISSUE THREAD

**Issue by Metal-Frog** [ndom91/briefkasten#8]
### Clear and concise description of the problem

Hallo,
danke für die tolle App!
Ich suche eine solche Lösung für mein Unternehmen - da wäre es aber zwingend erforderlich, öffentliche Lesezeichen zu haben, also solche, die für alle Nutzer sichtbar sind.
Wäre es möglich, dieses Feature in Briefkasten zu implementieren?

### Suggested solution

public bookmarks

### Validations

- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by ndom91** [comment]
Hi @Metal-Frog, thanks for the feature request!

Do you mean something like a "Category" or "Tag" you can mark as "Public", which can then be shared publically as a list. So that you could share your "Work" links via a link like, `https://briefkasten.vercel.app/metal-frog/work-links` ?

**Comment by Metal-Frog** [comment]
Hi,
thank you for your response.
Hm, I'm not shure if I get this right. Would be easier seeing an example.
I try to explain a bit more:
Image you have a department with 10 people. I think each one has to register himmselve (but also some kind of a gueast access without registration would be nice). Each user should be able to create personal links (only visible for him) and public links. All employees of the department should see the public list of links as default.

Regards, Tom

**Comment by ndom91** [comment]
Ah okay, so instead of a user being able to share a "group" or "folder" of links publicly - you're thinking more along the lines of having a shared company/organisation folder of links, i.e. each user from a company would still have to login, but then you could all manage one shared folder of links. 

Is that more along the lines of what you're thinking?

**Comment by Metal-Frog** [comment]
Close :)
If a link is public it can be seen by everyone (it doesn't have to be a specific folder).
Furthermore it would be ideal if every visitor can see the public links (without having to login first). And the public links can be edited by everyone who has an account.

**Comment by ndom91** [comment]
Okay I think I got it now :grin: 

You probably don't want _everyone_ who has a briefkasten account to be able to edit your shared folder though, right?

So this does necessitate some sort of "group" / "team" / "organisation" structure which can contain multiple users. Then you could create a category/folder within your "team", so every logged in member of the team can edit the contents of this category/folder of bookmarks. Also you could set the category/folder to "public" to make it publically read-only/visible. 

I think this is a nice feature request, but is pretty involved in terms of development requirement. 

I will definitely put it on the roadmap though so I don't forget!

**Comment by ndom91** [comment]
Going to close this issue. I did create a ticket for this feature request, however :+1:
